version: "3.8"

services:
  geoip-shell:
    build: .
    container_name: geoip-shell

    # Required for firewall manipulation
    network_mode: host
    privileged: true

    cap_add:
      - NET_ADMIN
      - NET_RAW

    env_file:
      - .env

    restart: unless-stopped
