services:
  geoip-shell:
#    build: .
    image: kiwilad-nz/geoip-shell-container
    container_name: geoip-shell
    environment:
      TZ: Pacific/Auckland
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    volumes:
      - ./geoip-shell/config:/etc/geoip-shell
      - ./geoip-shell/shell:/var/lib/geoip-shell
    restart: unless-stopped
